I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/storyscript.rpy", line 408, in script
    if toldonmarc == True:
  File "game/storyscript.rpy", line 408, in <module>
    if toldonmarc == True:
NameError: name 'toldonmarc' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/storyscript.rpy", line 408, in script
    if toldonmarc == True:
  File "C:\Users\501508\Desktop\renpy-6.99.8-sdk\renpy-6.99.8-sdk\renpy\ast.py", line 1647, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\501508\Desktop\renpy-6.99.8-sdk\renpy-6.99.8-sdk\renpy\python.py", line 1490, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\501508\Desktop\renpy-6.99.8-sdk\renpy-6.99.8-sdk\renpy\python.py", line 1485, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/storyscript.rpy", line 408, in <module>
    if toldonmarc == True:
NameError: name 'toldonmarc' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.99.8.959
High School Simulator 0.0
